spring.application.name=mercury


# Database Connection properties
spring.datasource.url=jdbc:mysql://localhost:3306/Mercury
spring.datasource.username=root
spring.datasource.password=Prashik@7597
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.physical_naming_strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
